### ISSUE TITLE
Polymorphic store

### ISSUE THREAD

**Issue by aubinlorieux** [gaearon/normalizr#12]
Hi there,

I was wondering how to deal with polymorphic store.
I have two stores ActionStore and FollowUpStore and each one can receive comments.

```js
var actionSchema = new Schema('actions', {idAttribute: 'id'});
var followUpSchema = new Schema('followUps', {idAttibute: 'id'});
var commentSchema = new Schema('comments', {idAttribute: 'id'});

actionSchema.define({
  comments: arrayOf(CommentSchema)
});

followUpSchema.define({
  comments: arrayOf(commentSchema)
});

comment.define({
  // followUp || action determine by the value of objectType field ('action' or 'followUp')
});
```

If I fetch by actions or followUps there is no problems. But when I store a new comment i need to push the new comment in the `comments` field in the ActionStore or the FollowUpStore.

Any idea ? 

Aubin

**Comment by babsonmatt** [comment]
+1

**Comment by gaearon** [comment]
Sorry, I don't understand :-(
Can you provide more context?

**Comment by aubinlorieux** [comment]
Yes,

On my API I only use one table to store comments. A user can post comments for Actions or FollowUps.

To determine if a comment is link to an action or a followUps I use two fields : objectType (name of the model class), objectId (id of the action or followUp).

When I store a new comment I get this response:
```json
{
  "id": 1,
  "comment": "a comment for the comment",
  "objectType": "action",
  "objectId": "1",
  "object": {
    "id": 1,
    "label": "a label",
    "comment": "a comment for the action"
  }
}
```

How to let normalizr parse my response to get the following result:

```js
var normalize = {
  entities: {
    comments: [{
      id: 1,
      objectType: 'action',
      objectId: 1,
      comment: "a comment for the comment"
      action: 1 
    }],
    // Only if objectType == 'action'
    actions: [{
      id: 1,
      label: "a label",
      comment: "a comment for the action"
      comments: [1]
    }]
  }
}
```

For now I've created two schemas for comment: ActionCommentSchema and FollowUpCommentSchema and I chose the one or the other depending on the context when the API respond. 

I hope this is more explicit: I don't know if it is possible to solve this problem with normalizr.

Thanks in advance.

**Comment by gaearon** [comment]
>For now I've created two schemas for comment: ActionCommentSchema and FollowUpCommentSchema and I chose the one or the other depending on the context when the API respond.

This seems like the right solution to me. I'm closing, but if there is enough interest in this, I'd consider a PR implementing some sort of polymorphism support.
