### ISSUE TITLE
How to iterate through JSON Object with members?

### ISSUE THREAD

**Issue by urbanvikingr** [gaearon/normalizr#15]
I understand that it is by design that articles is represented as JSON Object with members ```{ {} , {} }``` and not as JSON Array ```[ {}, {} ]```.

Since methods like map and forEach doesn't exist for JSON Object with members, I am wondering how iterations can be handled?

**Comment by xak2000** [comment]
You can use `for` loop.
```
for (var key in obj) {
  if (obj.hasOwnProperty(key)) {
    console.log(key + ": " + obj[key]);
  }
}
```

Or if you really want to use functional style programming you an use [lodash](https://lodash.com/) library (for example).

**Comment by urbanvikingr** [comment]
I did this, but it feels incorrect that arrayOf doesn't return array. I was wondering if there could be a better and generic way.

store.js:
````
let normalized = normalize(action.data, arrayOf(product));
      products = toArray(normalized.entities.products);
````

store_utils.js:
````
"use strict";

export function toArray(obj) {
  let array = [];
  Object.keys(obj).forEach(key => {
    array.push(obj[key]);
  })
  return array;
}
````

**Comment by xak2000** [comment]
I doesn't understand why you want to convert natural map of `id -> entity` to simple array in which you cannot then just get entities by their IDs.

In my applications I do the opposite as when I want for example to display the name of the author of article I can just do `authors[article.author].name`. (`article.author` is not object but just author's ID and `authors` is not array but map of authors keyed by their IDs).

I'm not using Flux or Normalizr but I planning to use Normalizr without Flux just for this convenient convertions from deep nested structures to plain `id->object` maps.

In any case if I understand correctly, `arrayOf` just defines the schema of response from the backend. Not the return value of `normalize` function. So I don't see any incorrectness that arrayOf doesn't return array. In returns the Schema which represents array of other Schemas.

**Comment by urbanvikingr** [comment]
Perhaps I just need to find out how iterate through articles grouped by their ID. Otherwise, I agree that I would prefer this structure over simple array.

**Comment by xak2000** [comment]
You already did it:
```
Object.keys(obj).forEach(key => {
    console.log(obj[key]);
  });
```

Or using lodash:
```
_.forEach(articles, function (article) {
  console.log(article);
});
```
Keys (article's `id` in this case) can be accessed as second function argument if needed (`function (article, id) {`).

**Comment by urbanvikingr** [comment]
I guess the lodash _.forEach method could work to pass each article as an object.

**Comment by urbanvikingr** [comment]
No issue to resolve.

**Comment by xak2000** [comment]
If you really want to convert result to array, you can use lodash for that `_.values(obj)`. It creates an array of the own enumerable property values of obj.

**Comment by urbanvikingr** [comment]
I think that @gaearon got it right. It is better to keep the JSON object format and convert to array where needed instead of converting to array when receiving data. There are several ways to convert JSON objects into array. @xak2000 and I have mentioned two of them above.

In fact, now the otherwise required getById function is no longer necessary, since the JSON objects are normalized with their Id as key.

**Comment by gaearon** [comment]
>If anybody was wondering, I am converting to array when rendering list of objects in view.

:+1:

And you can memoize the result with [reselect](https://github.com/faassen/reselect).

**Comment by falzhobel** [comment]
@gaearon Lots of interesting discussion here, would you have a simple example of how reselect would help in this case? I just can't seem to get my around the use of this at the moment. Right now what I do with a normalized JSON object is to simply pass it in lodash's `_.values()` when I need to iterate with array methods.

Short snippet:

```javascript
const mapStateToProps = (state) => {
  return {
    data: _.values(state.data)
  }
}
```

**Comment by enu-kuro** [comment]
@urbanvikingr How about just using map?
```
Object.keys(obj).map(key =>{
  return obj[key]
});
```

**Comment by urbanvikingr** [comment]
@enu-kuro Thank you. This issue has been resolved, since August 2015 :)
