### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by gyzerok** [gaearon/normalizr#19]
Is it possible to add GraphQL schema support for this? It feels redundant to create mutiple schemas and keep them in sync.

**Comment by gaearon** [comment]
I don't know :-). Feel free to try!

**Comment by gyzerok** [comment]
Close cuz for now I'm discussing about the normalize possibility in core of GraphQL.

**Comment by gyzerok** [comment]
You can check my solution: [prepare GraphQL schema](https://github.com/gyzerok/adrenaline/blob/master/src/utils/parseSchema.js) and [normalize](https://github.com/gyzerok/adrenaline/blob/master/src/utils/normalize.js)

**Comment by gaearon** [comment]
I don't plan to work on this so closing.
However I'd be happy to consider a PR that adds support for GraphQL (not sure how hard would that be).

**Comment by jmeas** [comment]
@gyzerok , do you have a working link to the schema and normalize call? I'm getting a 404 on those links now. No worries if not; I know it's been awhile.
