### ISSUE TITLE
Item remove issue

### ISSUE THREAD

**Issue by gyzerok** [gaearon/normalizr#21]
As I've understood this normalization perfectly suits for 3 of 4 crud operations. How to resolve case with ```REMOVE``` operation? How to correctly merge entities in this case?

**Comment by gaearon** [comment]
See some discussion here:

https://github.com/rackt/redux/issues/386#issuecomment-127051008
https://github.com/gaearon/flux-react-router-example/issues/30
https://github.com/gaearon/flux-react-router-example/issues/18

In short, use status to indicate item is deleted. Which is pretty much what you'd do on database level.

**Comment by gaearon** [comment]
(And if we're dealing with "deleting from list", just remove ID from array. Who cares if cached entity is in cache, if there are no links to it.)
