### ISSUE TITLE
Dealing with maps

### ISSUE THREAD

**Issue by unindented** [gaearon/normalizr#28]
I'm probably working with the weirdest payload ever, but it's a legacy API, so bear with me...

The beast looks something like this:

```js
{
  "messages": [{
    "id": 1,
    "body": "A message",
    "attachments": [{
      "id": 1,
      "type": "images",
      ...
    }]
  }],
  "replies": {
    "1": [{
      "id": 2,
      "body": "First reply",
      "attachments": [{
        "id": 2,
        "type": "images",
        ...
      }, {
        "id": 3,
        "type": "videos",
        ...
      }]
    }]
  }
}
```

So `messages` is an array of thread starters / OPs, and `replies` is a hash where the keys are message IDs, and the values are arrays of replies to the corresponding message.

I'd like to normalize both messages and replies as `message` entities, but I don't have a way of traversing the `replies` hash.

I was thinking of implementing a `mapOf` operator that would visit the values of a hash. The solution to my problem would then look like:

```js
var message = new Schema('messages')
var attachment = {
  images: new Schema('images'),
  videos: new Schema('videos')
}

message.define({
  attachments: arrayOf(attachment, {schemaAttribute: 'type'})
})

normalize(json, {
  messages: arrayOf(message),
  replies: mapOf(arrayOf(message)),
}
```

Does that sound useful?

**Comment by gaearon** [comment]
I'm OK with adding this, let's call it `valuesOf()`.

**Comment by unindented** [comment]
:+1: 

I'll work on a PR.

**Comment by unindented** [comment]
I was thinking that `mapOf`/`valuesOf` would return a hash, so the keys would be maintained:

```js
    input = {
      one: {
        id: 1,
        title: 'Some Article'
      },
      two: {
        id: 2,
        title: 'Other Article'
      }
    };
```

```js
  output = {
      result: {
        one: 1,
        two: 2
      },
      entities: {
        articles: {
          1: {
            id: 1,
            title: 'Some Article'
          },
          2: {
            id: 2,
            title: 'Other Article'
          }
        }
      }
    });
```

Does it make sense to name it `valuesOf`? You are not just keeping the values...

**Comment by gaearon** [comment]
Maybe I'm missing your point. I'm suggesting `valuesOf` as in “values of this object are of type X”. Is this the wrong interpretation?

**Comment by unindented** [comment]
Ah, if you read it like that then `valuesOf` makes sense. Ok, I'll work on the PR.

**Comment by gaearon** [comment]
Thanks. I gave you push access (but please don't commit to master).

**Comment by unindented** [comment]
Sure. Thank you.
