### ISSUE TITLE
Combine normalized objects?

### ISSUE THREAD

**Issue by tindli** [gaearon/normalizr#3]
Awesome lib - thanks.

Is there an easy way to combine normalized objects?
One can do this manually with _.merge()... but it
would be more comfortable to have this delivered by the lib.

**Comment by gaearon** [comment]
I think the lib should already do that if IDs match.

**Comment by gaearon** [comment]
https://github.com/gaearon/normalizr/blob/master/test/index.js#L304
https://github.com/gaearon/normalizr/blob/master/test/index.js#L379

**Comment by tindli** [comment]
Sorry... for the confusion but I mean
combining two normalized objects into one.

Lets say paginated data is fetched and we want
to have 1 normalized object in the store... 
How can the normalized data from the first fetch
and the normalized data from a second fetch
be combined?

Am I missing something?

**Comment by gaearon** [comment]
I think this is out of scope of this library.

Here's how I do it in my example project:

https://github.com/gaearon/flux-react-router-example/blob/master/scripts/stores/UserStore.js#L25
https://github.com/gaearon/flux-react-router-example/blob/master/scripts/utils/StoreUtils.js#L48

**Comment by tindli** [comment]
Ok thanks a lot!
