### ISSUE TITLE
Technique to Display universally/isomorphically rendered data

### ISSUE THREAD

**Issue by kanejoe** [gaearon/normalizr#37]
hi,

I have data which is successfully `normalize`d by the library.  But where in the lifecycle is the best point to do this?  

Is it overkill to normalize on the server and then on the client before re-hydrating into state?

What I have tried is call normalize on `componentWillMount` on the entry level component, but this is creating issues on re-render.

many thanks

**Comment by gaearon** [comment]
Either normalize on the server before returning API response, or on the client when handling it. There is no need to normalize both on server and on client. Do it in your AJAX callback.
