### ISSUE TITLE
Questions/Feature Requests: Nested entities that aren't objects, Denormalization, JSON-API

### ISSUE THREAD

**Issue by oyeanuj** [gaearon/normalizr#39]
Firstly, @gaearon, thank you for your work on the Redux ecosystem. The normalizr library has been critical for my project, so I had a couple of questions which are really disguised feature requests -

1. Are there any plans to support JSON-API response system in the future? Right now, I have made it work for JSON but there are plans to move to JSON-API in the near future. In that case, I wonder if I will have to discard library to write something similar of my own or if you plan to support it.

2. Is there any way to specify or for the dictionary to identify single attribute of an object rather than needing for the whole object to be there?

For example,

````Javascript
post.define({
	author: user
});
````
works great when the author object is embedded within the post object like
````JSON
"post": {
  "author": {
    "id": 5,
    "name": "r2d2"
  }
}
````

What can I do for cases where the JSON is **either of the two options** below?
````JSON
"post": {
  "author":5
}
````
OR
````JSON
"post": {
  "author_id":5
}
````

3. A pain that I am facing now is constant denormalization of the nested entities in a lot of the components. With a result, those components aren't as 'dumb' as I would like and are constantly having to have state.entities.x passed to them which they can use to fetch the appropriate nested entity (using lodash find, merge, mapValues etc). I suspect there is some other way of doing this? A different pattern or another denormalization solution?

Apologies if I missed this in documentation somewhere!
Thanks again!

**Comment by MikeBarnhardt** [comment]
I would also like to know if the JSON-API spec will be supported.

As far as `author` and `author_id` it sounds weird because usually in your schema or table you set the key. What type of database are you using?

If it's Mongo you can rename all keys easily in the CLI:

    db.posts.update({}, {$rename: {'author_id': 'author'}, {multi: true});

Which would take all existing `author_id` keys and change them to `author`.

**Comment by oyeanuj** [comment]
@MikeBarnhardt: The case of `author` & `author_id` seems to be fairly common in the Rails world where associations take the form of `has_one :author` and the key becomes `author_id`. In several cases, it is more performant to just show the foreign key than fetch an association and I would ideally have normalizr recognize the linkage between entities.

**Comment by MikeBarnhardt** [comment]
@oyeanuj Ah, that makes sense. I'm not familiar with Rails, but I can see where you might run into multiple keys now.

**Comment by ravloony** [comment]
I have this same problem with Laravel as a backend. I have activities belonging to markets. So I return activities with their market nested, which means a lot of duplication. I also have market_id as a property on activity, and would like to tell normalizr to use that, as I can fetch all markets from a different api call.

**Comment by vyorkin** [comment]
Concerning foreign key relations its easier to just [serialize foreign key references with a nested object](https://github.com/interagent/http-api-design/blob/master/responses/nest-foreign-key-relations.md). Serialization could be done completely independent of AR, ROM, etc model structure: jbuilder, activemodel serializers, etc.

**Comment by gaearon** [comment]
I'm happy to consider specific PRs. These suggestions might be great but they sound very open-ended, and since I don't actively work on this library, they are much more likely to be implemented if you work on them and send PRs :-). Thereby I'm closing.

**Comment by oyeanuj** [comment]
@gaearon thanks for your response! I might not have helped matters by clubbing a few different matters together. Before I can send PRs, I would love to get specific responses from you on the following points:

1. A pain that I am facing now is constant denormalization of the nested entities in a lot of the components. With a result, those components aren't as 'dumb' as I would like and are constantly having to have state.entities.x passed to them which they can use to fetch the appropriate nested entity (using lodash find, merge, mapValues etc). I suspect there is some other way of doing this? A different pattern or another denormalization solution? In general, it seems that denormalization isn't addressed much in this ecosystem, so I am wondering what is a good pattern for that?

2. Just to confirm, these are not supported yet by normalizr, right? Identifying the `author` has objects in cases where JSON resembles the following:

```javascript

"post": {
  "author":5
}

OR

"post": {
  "author_id":5
}
```



@vyorkin thanks for the suggestion, will try it!

**Comment by oyeanuj** [comment]
@paularmstrong I just wanted to follow up on above (especially the second request). Since I asked, there have been a lot of additions to the library. For the second request, is it something that `assignEntity` can be used for? And for the first request, is that something that this library has an opinion on?

**Comment by oyeanuj** [comment]
@paularmstrong Sorry, if the second problem wasn't clear. I'll try to clarify. 

In the example below,

````Javascript
post.define({
	author: user
});
````
works great when the author object is embedded within the post object like
````JSON
"post": {
  "id": 1,
  "author": {
    "id": 5
  }
}
````

and the normalized result would be something like this: 
````JSON
"result": [1],
"entities": {
  "posts": {
    "1": {
      "id": 1
    }
  },
  "users": {
    "5": {
      "id": 5,
      "name": "r2d2"
    }
  }
}
````
It seems that the entire author object needs to be embedded for the above example to work, i.e. get `users` entity. If instead the response from the API was something like **either of the two options** below, I wouldn't get the 'users' entity object (even though that response seems normalized)?

````JSON
"post": {
  "id": 1,
  "author":5
}
````
OR
````JSON
"post": {
  "id": 1,
  "author_id":5
}
````

So, an ideal solution would be to 
1. able to support a dictionary or array of terms for 'user', i.e., both author and author_id?
2. if instead of an object, an id is returned than that being translated to object.id?

Is it better to do this through `assignEntity` instead?

**Comment by paularmstrong** [comment]
Entities need to be objects. If all you're getting from the API is a number or string for the ID, normalizr does not and will not know how to turn that into an entity. Maybe I'm missing something, so it might be more clear if you posted your input and full expected output.

**Comment by oyeanuj** [comment]
(Sidenote: Are comments disappearing? I can't seem my previously posted comment with example input and output, or your comment which I only have as an email notification). To respond to your comment - Ideally, there would be a way to ensure that all three inputs below could result in the same output.


````JSON
"post": {
  "id": 1, 
  "author": {
    "id": 5
  }
}
````

OR 

````JSON
"post": {
  "id": 1,
  "author":5
}
````

OR

````JSON
"post": {
  "id": 1,
  "author_id":5
}
````

would all result in:

````Javascript
entities: {
  posts: {
    1: {
      id: 1,
      author: 5
    }
  },
  authors: {
    5: {
      id: 5
    }
  }
}
````

By default, only the first one results in the desired output, not all three. In Rails world for example, or in general for relational databases, often the foreign key is returned rather than the entire entity that the foreign key represents. 

I hope that clarifies the question, sorry for the back and forth on this!

**Comment by paularmstrong** [comment]
The second two "OR" options aren't entities. There's no way to normalize them. They're already normalized. You can convert the `author_id` key to `author` using `assignEntity`, if you'd like. However, it will not be possible to make that appear in the entities output.

**Comment by oyeanuj** [comment]
Thanks for the quick response! Is there a way to use `assignEntity` to convert last two options into entity since #72 gives us access to the original input object? If we do that, will the it appear in the entities output?

As an aside, philosophically, should dealing with references to an entity also be considered within the scope of this project as they serve the same purpose and contain the same functional information? I could see the library supporting ['key', 'key_id', 'keyId'] when determining an entity and if it is a number, assigning it to the 'id' field? It seems like that this might be a common use-case for anyone dealing with relational databases?

**Comment by paularmstrong** [comment]
You cannot convert objects during normalization to entities unless they are pre-defined as entities in the schema provided. So, no, `assignEntity` will do you no good here.

I'm not convinced on the need to have any magic conversion of keys. In a lot of cases, it doesn't make sense to change. Also, many object IDs are actually strings, so this wouldn't help in a lot of cases. I'd rather err on simplicity here and let the you, the developer, decide how to handle things for yourself.
