### ISSUE TITLE
Different entity on single key

### ISSUE THREAD

**Issue by tobiaskun** [gaearon/normalizr#40]
In this example `reference` can either be of type `shop_article` or `shop_outfit`. The function `valuesOf` treats the content as array and is looping over the keys.

```javascript
let reference = wish.define(
    shop_article: article,
    shop_outfit: outfit 
);

let example1 = {
    id: 1,
    _type: 'user_userhaswish',
    reference: {
        id: 1,
        type: 'shop_article'
    }
}

let example2 = {
    id: 1,
    _type: 'user_userhaswish',
    reference: {
        id: 1,
        type: 'shop_outfit'
    }
}
```

Is there a function like `valuesOf` that only expects one entity in the json?

**Comment by gaearon** [comment]
Should be out in 2.0.0 via the new `unionOf()` (#42).
