### ISSUE TITLE
side loading in API response

### ISSUE THREAD

**Issue by mmahalwy** [gaearon/normalizr#41]
How can normalizr deal with side loading? We have an api that talks to both a react-redux app and an ember app. Ember came earlier, therefore there are side loading structures implemented.

For example:

```
{
  user: {
    name: 'John Doe',
    activities: [1,2,3]
  },
  activities: [
    {
      id: 1,
      name: 'Snow boarding'
    },
    {
      id: 2,
      name: 'Soccer'
    },
    ...
  ]
}
```

**Comment by gaearon** [comment]
I don't understand the question. What is side loading, and how is it related to normalizr?

**Comment by xak2000** [comment]
Sideloading is a loading relations of  requested entities within the same response (without additional requests). For example if we request users then response will contain array of users, but also array of posts but only posts related to any of loaded users. So we can show all posts of each loaded user without additional requests. It's like loading relations inline but not inline. :)

The author's code example is good example of side-loading of `activities` when you requested just `user`.
Maybe more clear explanation [here](https://www.quora.com/What-is-Ember-js-sideloading).

I think the author of this issue just ask to support this responce structure by normalizr.

**Comment by mmahalwy** [comment]
@xak2000 couldn't have said it better myself! 

I guess the purpose of the issue was to get your thoughts @gaearon or others in the community on handling side loading with normalizr. Currently, since this issue is a bit dated, I ended up just doing
```
{
  user: arrayOf(user),
  activities: arrayOf(activity)
}
```

**Comment by cquinders** [comment]
@mmahalwy In my view the main purpose of `normalizr` is flattening deeply nested entities inside of JSON data. Since all of the nested entities in your example are already pulled out and referenced by id instead, there should be no need to use `normalizr` at all.

So if your example would look like this:
```json
{
  "id": "1",
  "name": "John Doe",
  "activities": [
    {
      "id": "2",
      "name": "Snow boarding"
    },
    {
      "id": "3",
      "name": "Soccer"
    }
  ]
}
```
`normalizr` would turn it into this:
```json
{
    "result": ["1"],
    "entities": {
        "users": {
            "1": {
                "id": "1",
                "name": "John Doe",
                "activities": ["2", "3"]
            }
        },
        "activities": {
            "2": {
                "id": "2",
                "name": "Snow boarding"
            },
            "3": {
                "id": "3",
                "name": "Soccer"
            }
        }
    }
}
```
For your sideloaded entities to look like the `normalizr` output you just have to put `user` and `activities` into an object, where they are keyed by id. This could be done by a reduce function:
```js
// payload is your JSON data
const {user, activities} = payload;

const entities = {
  users: {
    [user.id]: user
  },
  activites: activities.reduce((result, activity) => {
    result[activity.id] = activity;
    return result;
  }, {})
};
```

I hope that helped!

**Comment by mmahalwy** [comment]
@cquinders you're right, I found myself using normalizr just for having a key (id) value pair of my payload, which I can do with a reduce function like you did. I don't know what's common practice though in the redux community (whether storing key-value or an array and using `.find()` when finding objects). Thoughts? This might be beyond the scope of this issue

**Comment by cquinders** [comment]
@mmahalwy I think I would store entities in an object indexed by id if I want to find entities by their id most of the time. It’s faster. Think of looking up `activities` for a given `user` and the like ...

If there are no nested entities to look up and my UI heavily relies on filtered sets of entities, storing in an array and using `filter` may be the simpler solution.

But yeah, further discussion might be a little bit beyond the scope of this issue.

**Comment by mmahalwy** [comment]
@cquinders sounds good and i definitely agree with you about the object storage. that how i have it right now and decently content. Closing...
