### ISSUE TITLE
Issue with Babel 6

### ISSUE THREAD

**Issue by mehdichamouma** [gaearon/normalizr#44]
Hey,

For the same reasons as https://github.com/rackt/react-redux/issues/206 the lib is brokren when using Babel 6 (e.g. when using RN >= 0.16)

I suggest to merge this pull request to fix it : https://github.com/gaearon/normalizr/pull/43

:smiley:

**Comment by gaearon** [comment]
It isn't broken with Babel 6; it's only broken if you're processing `node_modules` with Babel which ideally you shouldn't do. Unfortunately RN gives you no choice, but it wasn't broken for other Babel 6 consumers.

Fixed in 1.4.1, please verify.
