### ISSUE TITLE
Working with ImmutableJS

### ISSUE THREAD

**Issue by meenie** [gaearon/normalizr#45]
I'm having a bit of an issue working with ImmutableJS when you pass in an object after running it through normalizr.  Something like this:

```typescript
let normalized = {
  result: [1, 2],
  entities: {
    articles: {
      1: {
        id: 1,
        title: 'Some Article',
        author: 1
      },
      2: {
        id: 2,
        title: 'Other Article',
        author: 1
      }
    },
    users: {
      1: {
        id: 1,
        name: 'Dan'
      }
    }
  }
}

const immutableObj = Immutable.fromJS(normalized);

console.log(immutableObj.getIn['entities']['articles'][1]);
// -> undefined
console.log(immutableObj.getIn['entities']['articles']['1']);
// -> {id: 1, title: 'Some Article', author: 1}
```

So if you itterate through `result` and use the values to pull out articles, it won't work unless you `toString()` them.  This is due to Immutable.map() allowing any types for keys, not just strings, like POJOs.

What do you think would be the best practice here? :)

**Comment by gaearon** [comment]
I don't know :-). Do you have any suggestions?

**Comment by meenie** [comment]
I ended up doing it [this way](https://github.com/ngrx/angular2-store-example/blob/master/src/app/models/users.ts#L57-L68). Much better this way because I can create `Record`'s for each user.  I'll close this off.

**Comment by m14t** [comment]
@meenie do you have an updated link to what your solution was?

**Comment by meenie** [comment]
@m14t: Sorry, I don't.  That repo got nixed in support of using https://github.com/ngrx/example-app.  But here's the code at that particular point in time: https://gist.github.com/meenie/af2e930d7ef5f3d570eac719504c9349#file-users-ts-L57-L68

Looking at it now, it doesn't make much sense ><.
