### ISSUE TITLE
Best practices to handle memory consumption of normalized data

### ISSUE THREAD

**Issue by slorber** [gaearon/normalizr#47]
I've posted a similar question about Relay here: https://github.com/facebook/relay/issues/720

What I understand of normalizr is that it invites people to add items in a normalized form to their stores. For example if we are dropbox and on a view we want to display some data related to the user and his friends, and his private files, we would perhaps fetch some users, fetch some files (as json metadata, not the content) in a single or multiple requests or whatever, and use something like Normalizr to populate the Flux/Redux stores. 

So the thing is, weither with Relay or Normalizr, we somehow retrieve progressively normalized data from a remote server, weither it is from REST API's or GraphQL.

The thing is we always explain how to add that data to the browser cache (I mean inside in Relay store or in Redux store), but nobody seems to care about when should we start to remove data from that cache.

I don't like at all the idea to have an ever-growing cache that takes progressively more and more memory, so are there anyone here that has thought about this?

Should I really care and could I consider that with normalized data on a non-extravagant app it's almost impossible that the user session fetch enough data to fill all the browser's memory and make it crash?

**Comment by gaearon** [comment]
I'll close as this was discussed before.

https://github.com/gaearon/normalizr/issues/21#issuecomment-135409566
https://github.com/rackt/redux/issues/386#issuecomment-127051008
https://github.com/gaearon/flux-react-router-example/issues/30
https://github.com/gaearon/flux-react-router-example/issues/18

**Comment by slorber** [comment]
thanks will check that thx

**Comment by slorber** [comment]
@gaearon I think we are not talking about the same thing here.

- You: talking about removing items in a stores (or flagging them with an `isDeleted=true`) after the user clicks some delete button
- Me: talking about user just doing readonly actions, and the stores becoming bigger and bigger and consuming more and more memory, on a memory limited device

In this issue: https://github.com/gaearon/flux-react-router-example/issues/18

> I don't clear stores.
> I think it's generally a bad idea to only hold “current” item in store and clear it when screen changes. Instead, it's much easier to store entities in an id -> entity map inside a store, and only query the current one from the component.

I understand your point of considering the stores like relational database tables but the difference with relational databases is that the servers can have a lot more memory, and some part of the data remains in disc. A browser has a limited amount of memory.

If the user is using an app for a very long time and the stores continue growing over time, isn't there a risk to make the browser crash if you never remove items from the stores at all?

I don't find the memory consumption aspect discussed in any of your links

**Comment by gaearon** [comment]
From one of those links:

>You can make schema a first class concept, just like it's first class in normalizr. If you have a schema, you can write a reducer factory that creates reducers adhering to this schema. These reducers will know when to remove IDs from foreign key fields because they know what the schema looks like.

This kind of manual garbage collection is doable, I just never felt the need for it. A sensible moment to attempt is when user switches routes, for example.

**Comment by slorber** [comment]
Not sure to understand your quote :)

Yes the manual garbage collection is doable, I could put a TTL for each record in a store or use some kind of LRU system. The problem is that it seems hard to know which items inside the store are currently in use inside the react views, because we don't want to GC that data

**Comment by gaearon** [comment]
>The problem is that it seems hard to know which items inside the store are currently in use inside the react views, because we don't want to GC that data

If the schema as a first-class thing with a public API to traverse it (it's currently not), technically you'd be able to traverse the entities and "mark" those that are currently in use based on "collections" (arrays of IDs). This would work as a manual garbage collection.

**Comment by dustingetz** [comment]
react-cursor has a similar issue, this is how i believe it can be solved, i have not implemented it yet http://stackoverflow.com/questions/34202895/need-weakmap-a-b-c

**Comment by dustingetz** [comment]
What i think you want, is if the react cmp (for example) using some object is gc'ed, the object will also be gc'ed from the normalizr cache

**Comment by dustingetz** [comment]
btw this is not a theoretical leak in the server-side-rendering case (at least for react-cursor but your use case feels similar)

**Comment by slorber** [comment]
thanks I'll check your link when I have time.

Yes I want the normalizr (or Relay) cache to be able to cleanup when the underlying data is not rendered. Not necessarily immediately though as it makes sens to keep the data for a while in case we want to display again that object.

**Comment by dustingetz** [comment]
> cleanup when the underlying data is not rendered. Not necessarily immediately though as it makes sens to keep the data for a while in case we want to display again

I think if we are clever we can combine LRU cache (or time based or whatever strategy) with multi-level WeakMap to achieve this

**Comment by slorber** [comment]
Joseph Savona has given a nice answer about memory management in Relay (experimental GC to be released).
https://github.com/facebook/relay/issues/720#issuecomment-174050321

> Currently, Relay does not evict data from its (in-memory) cache under the default configuration. This means that memory usage may grow during the course of a session, and that all data is cleared e.g. when the user closes the browser tab.
>In practice, we've found that this isn't a problem for most apps. Because of the cyclic nature of social graphs there's a often significant amount of overlap in content, and as a result memory usage can grow more slowly than one might intuitively expect.

David Nolen also said that Om Next would handle memory management (no more details)

**Comment by dustingetz** [comment]
i think Om Next handles this problem by leveraging http layer caching - Om Next does not do javascript layer caching, per my understanding. An Om Next application will contain a nested GraphQL-like query to get the precise total data required to render the app, and Om Next will send the query to the backend endpoint that handles all queries with the hash of the query in the url so that it is cachable at http layer. There are some tweets about this and I have had a small amount of email correspondence and in person discussion with him on this topic.
