### ISSUE TITLE
Odd EntitySchema property mutation when trying to add new functionality

### ISSUE THREAD

**Issue by smargh** [gaearon/normalizr#49]
Alright, this is a tricky problem that will be hard for me to describe, primarily because it is a problem I've hit in trying to add one piece of functionality to Normalizr. So, this is not an "actual bug", but it feels like some sort of bug, even if it currently doesn't seem to negatively affect anything.

Let me begin by describing the feature I'm trying to add. I want to be able to hydrate certain entities with default UI state data as I normalize. So, for example, let's say that in my UI, all of the articles are accordion panels, so I want all new articles (retrieved from the API) to have an `accordionOpen` property set to `false`. Now, the data returned from the API does not have this property, and why would it. What I envisioned was an interface like this:
```
const article = new Schema('articles', {template: {accordionOpen: false});
const user = new Schema('users');
const collection = new Schema('collections');
```

Internally, `EntitySchema` adds this code to the constructor `this._template = options.template || {};` and then adds a simple `getTemplate` method. The only other change is then to `visitEntity`:
```
function visitEntity(entity, entitySchema, bag, options) {
  console.log('***visitEntity', entity);
  const {
    mergeIntoEntity = defaultMergeIntoEntity
  } = options;

  const entityKey = entitySchema.getKey();
  const id = entitySchema.getId(entity);
  const template = entitySchema.getTemplate();

  if (!bag.hasOwnProperty(entityKey)) {
    bag[entityKey] = {};
  }

  if (!bag[entityKey].hasOwnProperty(id)) {
    bag[entityKey][id] = template;
  }

  let stored = bag[entityKey][id];
  let normalized = visitObject(entity, entitySchema, bag, options);
  mergeIntoEntity(stored, normalized, entityKey);

  return id;
}
```

Instead of initializing `bag[entityKey][id]` to an empty object, use the template object (which, recall, defaults to an empty object). 

Now, I *think* this approach will work, but I've been unable to fully test it because of the "bug" that this issue is actually about: for whatever reason `mergeIntoEntity` has the side-effect of mutating `entitySchema._template`. Before that function is called `entitySchema._template` will equal what you expect; after the function is called `entitySchema._template` will equal `normalized`. You can observe this phenomenon in [this CodePen](http://codepen.io/pmacsx/pen/bEVWyr).

I have a few thoughts, but no real sense of what's going on. First, `entitySchema` is not passed into `mergeIntoEntity` directly, so this is a secondary effect mutation. Second, `entitySchema` *is* passed into `visitObject` to build the `normalized` var, so this seems to me where the reference is made and thus how `mergeIntoEntity` can mutate `entitySchema`. Third, `entitySchema._key` *does not* mutate, and neither does `entitySchema._getId`; so, is the mutation because `entitySchema._template` is an object?

As I said, I can't quite see what's going on, but I would love to either [A] fix the issue so that I can implement the feature I need, or at the very least [B] learn a bit more about JS to understand what the hell is happening here.

stephen

**Comment by smargh** [comment]
Thinking about it from another angle, I realized that we need not mutate the `stored` object at all; we could simply re-assign it. One solution would be to remove the `let stored = bag[entityKey][id];` line altogether and replace `mergeIntoEntity(stored, normalized, entityKey);` with `bag[entityKey][id] = Object.assign({}, bag[entityKey][id], normalized);`. I have tested and this solution does appear to work as expected.

**Comment by gaearon** [comment]
I don't think this use case is something that we want to support solving in normalizr.
Generally you're free to "select" and manipulate your data *after* it is processed by normalizr.
This includes putting "default" data in it, augmenting it, aggregating, etc.
A library like [reselect](https://github.com/rackt/reselect) can help you apply selectors efficiently with memoization.
