### ISSUE TITLE
Define relationships in Schema constructor

### ISSUE THREAD

**Issue by TryingToImprove** [gaearon/normalizr#5]
It would be cool if it was possible to define the relationships in the `Schema` constructor

    import { arrayOf, Schema } from "normalizr";

    var Employee = new Schema("employees");

    var Medication = new Schema("medications");

    var MedicationHistoryItem = new Schema("historyItems", {
        employee: Employee,
        medication: Medication
    });

instead of 

    var MedicationHistoryItem = new Schema("historyItems");
    MedicationHistoryItem.define({
        employee: Employee,
        medication: Medication
    });

**Comment by gaearon** [comment]
The reason for this API is to allow circular dependencies.
With contructor-ish API, it would not obvious that they are supported (and they are).

**Comment by gaearon** [comment]
To clarify: if we left *only* constructor API, we wouldn't be able to have circular deps at all. (They turn out to be useful so I wouldn't like that.)

If we added constructor API *in addition* to method API, it wouldn't be obvious how to add a circular dependency to a code *already using* constructor API.

Do you still stand by thinking it's desirable?

**Comment by TryingToImprove** [comment]
Yeah I see.. I think that this is looking a little weird

    var MedicationHistoryItem = new Schema("historyItems");
    MedicationHistoryItem.define({
        employee: Employee,
        medication: Medication
    });

What about making the `define`-function return the Schema, so it would be more fluent instead? Or maybe have a `schemes`-option.

    var MedicationHistoryItem = new Schema("historyItems", { 
        schemes: {
            "default": { // properbly a different name because of reserved word
                employee: Employee,
                medication: Medication
            }
        }
    });

So it forces you to only declare relationship one place in the code, this might help when the API changes..

**Comment by gaearon** [comment]
I'd say I'd live with a more verbose but “stupid” API. If we break people's code, there should be a good reason to do so.

**Comment by gaearon** [comment]
I think I'll close this out. I see where you're coming from but I want to keep API really dumb, have a single way to set up any relationship—including a circular one.

Please feel free to comment if you have other arguments for this or API suggestions!

**Comment by TryingToImprove** [comment]
@gaearon  I have tried making a test for circular relationships, but I can't see why anyone would ever do that, the JSON would loop forever.. Can you provide a example?

    it('can normalize circular dependencies', function() {
      var employee = new Schema("employee");
      var workplace = new Schema("workplace");

      var input = {
        employees: [
            {
                "id": 1,
                "name": "Myrtle Randolph",
                "workplace": {
                    "id": 1,
                    "name": "RONBERT"
                }
            }
        ],
        workplaces: [
            {
                "id": 1,
                "name": "RONBERT",
                employees: [
                    {
                        "id": 1,
                        "name": "Myrtle Randolph"
                        // I cant put `workplace` here because of circluar dependency
                    },
                    {
                        "id": 2,
                        "name": "Nieves Walton"
                        // I cant put `workplace` here because of circluar dependency
                    }
                ]
            }
        ]
    };

      employee.define({
          workplace: workplace
      });

      workplace.define({
          employees: arrayOf(employee)
      });

      var dataSet = {
          employees: arrayOf(employee),
          workplaces: arrayOf(workplace)
      };

      normalize(input, dataSet).should.eql({
        result: {
            employees: [1, 2],
            workplaces: [1]
        },
        entities: {
            employee: {
                1: {
                    "id": 1,
                    "name": "Myrtle Randolph",
                    "workplace": 1
                },
                2: {
                    "id": 2,
                    "name": "Nieves Walton",
                    "workplace": 1
                }
            },
            workplace: {
                1: {
                    "id": 1,
                    "name": "RONBERT",
                    "employees": [1, 2]
                }
            }
        }
      });
    });

In this test I would expect that "Nieves Walton" would be normalized; but it does not..

**Comment by gaearon** [comment]
I added [some tests on recursive definitions](https://github.com/gaearon/normalizr/commit/51b313d83ff28aac30b38e53ca0ea3f1b1f74f94) and they pass.

In fact your test passes for me too, if I put

```js
                      "workplace": {
                          "id": 1,
                          "name": "RONBERT"
                      }
```

at the lines you marked with

```js
                    // I cant put `workplace` here because of circluar dependency
```

and fix

```js
          employees: [1, 2],
```

in assertion to be 

```js
          employees: [1],
```

since you only have one employee in the original object.

Here's the whole test passing:

```js

  it('can normalize circular dependencies', function() {
    var employee = new Schema("employee");
    var workplace = new Schema("workplace");

    var input = {
      employees: [
          {
              "id": 1,
              "name": "Myrtle Randolph",
              "workplace": {
                  "id": 1,
                  "name": "RONBERT"
              }
          }
      ],
      workplaces: [
          {
              "id": 1,
              "name": "RONBERT",
              employees: [
                  {
                      "id": 1,
                      "name": "Myrtle Randolph",
                      "workplace": {
                          "id": 1,
                          "name": "RONBERT"
                      }
                  },
                  {
                      "id": 2,
                      "name": "Nieves Walton",
                      "workplace": {
                          "id": 1,
                          "name": "RONBERT"
                      }
                  }
              ]
          }
      ]
  };

    employee.define({
        workplace: workplace
    });

    workplace.define({
        employees: arrayOf(employee)
    });

    var dataSet = {
        employees: arrayOf(employee),
        workplaces: arrayOf(workplace)
    };

    normalize(input, dataSet).should.eql({
      result: {
          employees: [1],
          workplaces: [1]
      },
      entities: {
          employee: {
              1: {
                  "id": 1,
                  "name": "Myrtle Randolph",
                  "workplace": 1
              },
              2: {
                  "id": 2,
                  "name": "Nieves Walton",
                  "workplace": 1
              }
          },
          workplace: {
              1: {
                  "id": 1,
                  "name": "RONBERT",
                  "employees": [1, 2]
              }
          }
      }
    });
  });
```

Did you mean something different?

**Comment by gaearon** [comment]
>I can't see why anyone would ever do that, the JSON would loop forever.

In a perfect world, it will. In a non-perfect world, you might want to have *a little* recursive info where leaf nodes are not “complete” (don't drag any subdependencies).

For example,

```js
user: {
  id: 2,
  thumbnail_url: 'http://nice.jpg',
  name: 'Dan',
  last_articles: {
    title: 'Nice article,
    liked_by: [{
      // ouch! it's user again
      // this time, we don't need to go further—it's enough info to show like counter
      id: 2,
      thumbnail_url: 'http://nice.jpg',
      name: 'Dan'
    }, {
      id: 3,
      thumbnail_url: 'http://nice2.jpg',
      name: 'Emily'
    }]
  }
}
```

**Comment by TryingToImprove** [comment]
Okay, cool. I think I get it now.. Thanks for the example.. + unit-test.. :) :+1:
