### ISSUE TITLE
Qu: Why assignEntity.call(null, normalized, key, entity)?

### ISSUE THREAD

**Issue by smargh** [gaearon/normalizr#50]
I'm trying to fully understand some of the implementation details of Normalizr, both to be able to adapt it for my own use, but also simply to better understand JS. In that vein, I was wondering why `visitObject` calls the `assignEntity` function with a `null` `this` context? In my (limited) testing, `assignEntity(normalized, key, entity)` worked precisely the same way.

**Comment by gaearon** [comment]
There is no reason, it was just an artefact of refactoring in https://github.com/gaearon/normalizr/commit/9d064e731662183a0487f533336c229e29345bad. It used to be `options.assignEntity()` which used `options` as context, I changed that to `.call()` but later decided to use destructuring forgetting to remove `.call()` now that it was no longer necessary. Feel free to send a PR removing it.
