### ISSUE TITLE
JSON responses with root keys

### ISSUE THREAD

**Issue by smargh** [gaearon/normalizr#55]
The API that I am consuming wraps all resource responses in a root key. So, for example, I might get a response like this:
```
{
  "cores": [
    {
      "id": 1,
      "name": "Translational Core Lab",
      "short_name": "TCL"
    },
    {
      "id": 2,
      "name": "Cell Center Stockroom",
      "short_name": "Stockroom"
    }
  ]
}
```
or like this:
```
{
  "core": {
    "id": 1,
    "name": "Translational Core Lab",
    "short_name": "TCL"
  }
}
```

In its current version, Normalizr does not handle JSON responses of this sort very nimbly, particularly when I am attempting to define a omni-schema that will handle all of my API responses, like in the README.

It is possible to achieve the effect I want, but it requires me making a "wrapper" entity that has associations to the two possible responses I could get for a resource (item or collection); like so:
```
const core = new EntitySchema('cores');
core.define({
  core: core,
  cores: arrayOf(core)
});
```

This is a bit (a lot?) confusing to read and to parse, but it also generates slightly improper output. If we were to take the two examples given above and normalize them with this `core` schema, we'd get these two outputs:
```
{
  "entities": {
    "cores": {
      "1": {
        "id": 1,
        "name": "Translational Core Lab",
        "short_name": "TCL"
      },
      "undefined": {
        "core": 1
      }
    }
  }
}
```
and 
```
{
  "entities": {
    "cores": {
      "1": {
        "id": 1,
        "name": "Translational Core Lab",
        "short_name": "TCL"
      },
      "2": {
        "id": 2,
        "name": "Cell Center Stockroom",
        "short_name": "Stockroom"
      },
      "undefined": {
        "cores": [
          1,
          2
        ]
      }
    }
  }
}
```

In both cases, and `undefined` key is set which has a reference to the actual entities. 

My question is whether or not this use-case would be worth a PR, and if so, in what way?

I have a fix ready which adds a new schema class (`RootSchema`) where you specify a singular key (e.g. `core`) and a plural key (e.g. `cores`) on initialization (e.g. `const core = new RootSchema('core', 'cores');`) and a new `visitRoot` function to handle parsing such schemas. 

This solution works perfectly for me, but I'm not certain if it's best, as I now simply create *all `RootSchema`s* and never any `EntitySchema`s, since I need this flexibility. So, I could conceive of a PR that would add this functionality to `EntitySchema` directly (not add a new schema class), but that would then alter the Normalizr API somewhat.

So, before I put in a PR, I wanted to just open up discussion about this issue and possible solutions.

stephen

**Comment by gpfunk** [comment]
In the normalize function call you can specify the field for the function to parse on, so for instance rather than writing `normalize(json, schema)` you can write `normalize(json, { cores: schema})`

**Comment by marcuswhit** [comment]
Thanks @gpfunk, this was what I needed too.

**Comment by eeynard** [comment]
Hi guys,

I have basically the same problem and I can't have the result I want. 
Here are my API response: 

```javascript
// Multiples
{
  "users": [
    {
      "id": 1,
      "name": "John Doe"
    },
    {
      "id": 2,
      "name": "Jane Doe"
    }
  ]
}

// Single
{
  "user": {
    "id": 3,
    "name": "Chuck Norris"
  }
}
```
And here are the normalize function calls

```javascript
const usersSchema = new Schema('users');

// Multiples
normalize(json, { users: arrayOf(usersSchema) })

// Single
normalize(json, { user: usersSchema })
```
And finally here are the results I get 
```javascript
// Multiples 
{
  entities: {
    users: {
      1: { id: 1, name: "John Doe" },
      2: { id: 2, name: "Jane Doe" }
    }
  },
  result: {
    users: [ 1, 2 ]
  }
}

// Single
{
  entities: {
    users: {
      3: { id: 3, name: "Chuck Norris" }
    }
  },
  result: {
    user: 3
  }
}
```
The "Multiples" normalized object is ok but the "Single" one has not the same structure. Here is what I would like to have
```javascript
// Single
{
  entities: {
    users: {
      3: { id: 3, name: "Chuck Norris" }
    }
  },
  result: {
    // user: 3 <-- what I have
    users: [ 3 ] // <-- what I want
  }
}
```

Can you help me ?
