### ISSUE TITLE
Normalizing tree-like data

### ISSUE THREAD

**Issue by ianmstew** [gaearon/normalizr#61]
@gaearon, I have appreciated and adopted your opinions on keeping data de-nested while in state (logically equivalent to database tables) and then querying through selectors (logically equivalent to database queries).  What do you think of _tree-like_ data, however?

For example, take the following tree:

```js
{
  name: 'a',
  children: [
    {
      name: 'b',
      children: []
    },
    {
      name: 'c',
      children: []
    }
  ]
}
```

One idea for normalization is a node registry based on path or otherwise unique id:

```js
nodeByPath: {
  'a': { name: 'a', children: ['a/b', 'a/c'] },
  'a/b': { name: 'b', children: [] },
  'a/c': { name: 'c', children: [] }
},
trees: ['a']
```

This seems to be the logical conclusion of a normalization strategy for trees that avoids nested data within state, but this approach presents a few challenges:

1. "Trimming" a branch off the tree now involves a traversal of that branch's descendants in order to remove from the node registry.
2. "Splicing" a branch into the tree again involves a traversal of that branch's descendants.
3. Re-constituting the tree for representation in a tree-like component is a little more challenging than expanding an array of id's into their respective complete objects (recursion is needed rather than a simple map).

Another approach would be node-local normalization:

```js
{
  name: 'a',
  children: ['b', 'c'],
  childrenByName: {
    'b': { name: 'b', children: [], childrenByName: {} },
    'c': { name: 'c', children: [], childrenByName: {} }
  }
}
```

The node-local approach permits path lookups by id, but it still doesn't solve nesting.

What are you thoughts in this case?  My guess is that it depends somewhat on the ultimate use, but I'm interested in your thoughts.  Thanks for all your work advocating for patterns over libraries (and for the less-is-more approach of the libraries you do advocate).

**Comment by gaearon** [comment]
It really depends ;-) Very hard to pick a particular shape until you know which operations you optimize for.

**Comment by ianmstew** [comment]
Haha, I suspected as much.  Thank you for confirming there is no silver bullet...  I'll keep an eye on my use case, then.
