### ISSUE TITLE
How do I normalize an object of values?

### ISSUE THREAD

**Issue by tarjei** [gaearon/normalizr#67]
Hi, I got an object like this:
```js
course : {
 modules {
   1: {id: 223},
   2: {id: 123},
   xxx
}
```

Is there a way I can define a custom function for serializing these modules?

Also, does the API contain a method to go from an object and to it's denormalized state?

**Comment by hadimichael** [comment]
I've noticed that `arrayOf()` will extract ids as keys, but it doesn't nomalise into an array. I have had to use `Object.keys()` as a workaround.

Keen to hear if there's a better approach.

**Comment by gaearon** [comment]
This should be covered by [`valuesOf()`](https://github.com/gaearon/normalizr#valuesofschema-options).
