### ISSUE TITLE
Ability to transform value of idAttribute

### ISSUE THREAD

**Issue by valerybugakov** [gaearon/normalizr#71]
Is there a way to transform value of idAttrbute when normalizing received JSON?
Use case from real-world redux example:
Github API can search users regardless of letter case. Requests to https://api.github.com/users/val and https://api.github.com/users/Val will return the same user.

If I query `val` and actual user has saved login `Val` and I use Schema
`const userSchema = new Schema('users', { idAttribute: 'login' })`
then I won't be able to get user out of state by
```
const mapStateToProps = (state, ownProps) => {
  const { username } = ownProps.params

  return {
    user: users[username] // username === 'val', but stored in state under 'Val'
  }
}
```
It would be great to have an ability to process (e.g. lowerCase) value of idAttribute with normalize function.

**Comment by paularmstrong** [comment]
You can pass a function to `idAttribute` that transforms the login to a lowercase string

```
const userSchema = new Schema('users', { idAttribute: (entity) => entity.login.toLowerCase() })
```

**Comment by valerybugakov** [comment]
@paularmstrong Thanks, missed that one in the docs!
