### ISSUE TITLE
How to update a single entity?

### ISSUE THREAD

**Issue by sibeliusseraphini** [gaearon/normalizr#75]
I have this shape of entities:

`state = { documents: {}, users: {}}`

how do I update a value inside a `document`?

**Comment by paularmstrong** [comment]
You can use the `assignEntity` function option to modify values (documentation in README)

**Comment by sibeliusseraphini** [comment]
@paularmstrong 

My current code is:

```js
import merge from 'lodash/merge';
import * as types from '../actions/action-types';

const initialState = {
  documents: {},
};

export default function entities(state = initialState, action = {}) {
  if (action.response && action.response.entities) {
    return merge({}, state, action.response.entities);
  }

  switch(action.type) {
    case types.DOCUMENT_DOWNLOADED: {
      //TODO improve this
      return Object.assign({}, state, {
        documents: {
          ...state.documents,
          [action.id]: {
            ...state.documents[action.id],
            path: action.path
          }
        }
      });
    }
  }

  return state;
}
```

Can I change the `Object.assign` to `assignEntity`? could you provide an example please?

**Comment by sibeliusseraphini** [comment]
@gaearon I think you should consider adding this to the [real-world](https://github.com/reactjs/redux/tree/master/examples/real-world) example

You don't update need of your entities in the example, so it doesn't really represent a real-world case

Thanks for all this awesome tools that we have built

**Comment by sibeliusseraphini** [comment]
this solves my problem - http://stackoverflow.com/questions/34954726/how-do-you-add-remove-to-a-redux-store-generated-with-normalizr
