### ISSUE TITLE
Possible dealing with this kind of format ?

### ISSUE THREAD

**Issue by minipai** [gaearon/normalizr#77]
We have a strange API format
```
[
  {user: {id: 1, name: 'foo'}},
  {user: {id: 2, name: 'bar'}},
  {user: {id: 3, name: 'wtf'}},
]
```
I can normalize with schema ` arrayOf({user: new Schema('users')}) ` 

to get 
{
  entities: {1:{id: 1, name: 'foo'}, 2: {id: 3, name: 'bar'}, 3: {id: 3, name: 'wtf'} },
  results: [{user: 1}, {user: 2}, {user: 3}]
}

however I hope results is [1,2,3].
Is it possible?

**Comment by paularmstrong** [comment]
Not at this time, unfortunately.
