### ISSUE TITLE
A marshal function to reassemble the object

### ISSUE THREAD

**Issue by mschipperheyn** [gaearon/normalizr#78]
Normalization is great for storing data in a more efficient way.

However, when you actually use the data, you often want the object "back together". As such it would be nice to have a marshal function that marshals all the related entities based on a Normalized object and a provided schema. 

It would be even cooler if this could be in a kind of lazy loading manner by putting a proxy in the place of the id reference which would only marshal the related entity when called. This is effectively how JPA tools such as Hibernate work.

**Comment by gpbl** [comment]
I was looking for this as well. I have different nested objects and it's tedious to extract entities etc. Often while developing I even forget some. `mapStateToProps` function can get [complicated](https://github.com/reactjs/redux/blob/master/examples/real-world/containers/RepoPage.js#L75).

As a simple API I'm thinking to:

```is
denormalize(schema, obj)
```

**Comment by gpbl** [comment]
I've published this: https://github.com/gpbl/denormalizr some minutes before discovering https://github.com/dehbmarques/denormalizr-immutable :smile:

**Comment by mschipperheyn** [comment]
Yeah, looks very much like the demoralize I wrote myself. I'm no expert on javascript performance but I wonder what the impact of using proxies to avoid unnecessary denornalization would be

**Comment by mschipperheyn** [comment]
Demoralize should obviously be denormalize :-)

**Comment by gpbl** [comment]
What do you mean for unnecessary denormalization?

**Comment by mschipperheyn** [comment]
Well, if your objects are extensive, you might be spending a lot of time denormalizing referenced object that you won't need. In the land of JPA / Hibernate, they basically "lazy load" those references, in stead of retrieving the object when the object is created, they set a proxy so that when you call a method on the proxied object, it will retrieve the object and make it available on the fly.

But in the case of JPA / Hibernate, you're actually hitting the database for those referenced objects, so you save a lot of time by proxying them until you need them. I'm not sure if this makes sense here, since the data is already there, and you're just saving some processing time

**Comment by paularmstrong** [comment]
Please see [#20](https://github.com/gaearon/normalizr/pull/20#issuecomment-168341075)

**Comment by paularmstrong** [comment]
So, I'm going to eat my hat. #214
