### ISSUE TITLE
Couldn't find mappedBy method in Schema.prototype

### ISSUE THREAD

**Issue by kaze13** [gaearon/normalizr#83]
I can't use `Schema.prototype.mappedBy(foreignKey)`  with version 2.0.1.

After checking the source code, I found there is no such method...

**Comment by kaze13** [comment]
I think the NPM repo is out dated.

**Comment by albertorestifo** [comment]
I'm having the same issue

**Comment by albertorestifo** [comment]
As a temporary fix, remove it and reinstall it from the github repo:

```
$ npm install gaearon/normalizr
```

**Comment by downsider** [comment]
The `mappedBy` method hasn't been released yet; it was pulled into master two days ago.

Any chance we could have a new release for this please?

**Comment by albertorestifo** [comment]
Why close the issue? It is not yet resolved.
