### ISSUE TITLE
Typos in mappedBy documentation?

### ISSUE THREAD

**Issue by dounan** [gaearon/normalizr#87]
Trying to wrap my head around the new mappedBy feature and noticed some potential errors in the example.

1) Should it be project.mappedBy?
```javascript
user.define({
  projects: user.mappedBy('collaborators'),
});
```

2) Should the second project have id: 2?
3) Should the result be a number instead of an array?
```javascript
{
  result: [1],
  entities: {
    users: {
      1: { id: 1, projects: [1, 2] }
    },
    projects: {
      1: { id: 1, collaborators: [1] },
      2: { id: 1, collaborators: [1] }
    }
  }
}
```

**Comment by YoruNoHikage** [comment]
Oops, you are right, my mistakes. Could you open a PR to correct these ?

**Comment by dounan** [comment]
Looks like the feature has been reverted. Closing.

https://github.com/gaearon/normalizr/pull/80#issuecomment-206957386
