### ISSUE TITLE
How to retain sort order from the server?

### ISSUE THREAD

**Issue by charleskirk** [gaearon/normalizr#9]
Because of using IDs for indexes, we lose sort order. I'd prefer not to duplicate this logic on the front-end and back-end... any ideas?

**Comment by gaearon** [comment]
The sort order is retained in the ID lists. It's just that entities themselves are extracted into maps.

Before:

```js
[{
  id: 2,
  title: 'Other Article',
  author: {
    id: 1,
    name: 'Dan'
  }
}, {
  id: 1,
  title: 'Some Article',
  author: {
    id: 1,
    name: 'Dan'
  }
}]
```

After:

```js
{
  result: [2, 1], // <----- your sort order is retained here!
  entities: {
    articles: {
      1: {
        id: 1,
        title: 'Some Article',
        author: 1
      },
      2: {
        id: 2,
        title: 'Other Article',
        author: 1
      }
    },
    users: {
      1: {
        id: 1,
        name: 'Dan'
      }
    }
  }
}
```

**Comment by charleskirk** [comment]
Ah makes total sense. Thanks for the super fast response!

**Comment by ty-dev** [comment]
How about maintaining order from the server for the child objects, for example:

```
[{
  id: 2,
  title: 'Other Article',
  publishDate: '2014-08-02',
  author: {
    id: 11,
    name: 'Bob'
  }
}, {
  id: 1,
  title: 'Some Article',
  publishDate: '2014-10-02',
  author: {
    id: 10,
    name: 'Dan'
  }
}]
```

And I want to list out the authors in order of publication date.

**Comment by xak2000** [comment]
@ty-dev How your example differs from the first? If your server return these objects ordered by date, they will still be ordered by date in normalized array, like in @gaearon  example. Normalizr just preserves the order of your data in resulting array of IDs. If objects were been ordered by date - their IDs in resulting array will be ordered exactly the same way.
