### ISSUE TITLE
Using the UMD build variant of the Normalizr

### ISSUE THREAD

**Issue by parallelthought** [gaearon/normalizr#95]
I'm trying to use Normalizr with Redux in an existing Java project (maven). In order to keep the start off time to the shortest, I've not yet used any package or module managing plugins.

So currently I'm using a UMD build of Redux and have included it using the `<Script>` tag in the HTML page. I'm looking for a similar approach to use Normalizr as well.

I see that the NPM version has a [minified file](https://npmcdn.com/normalizr@2.0.1/dist/normalizr.min.js) included in its dist folder. 

However I'm not able to figure out as to how I can use the functions (such or normalize() or create a new Schema). Is there any global variable which Normalizr exports through which I can invoke these APIs (like Redux is made available as a global variable through `window.Redux`) or is there any other better way ?

Appretiate any help on this.

**Comment by mahajansohan312** [comment]
You can definitely use **window.normalizr** it will give you access to Schema,arrayOf,normalize,unionOf,valuesOf. Pretty much everything needed.

**Comment by parallelthought** [comment]
Thanks for the inputs @mahajansohan312
