### ISSUE TITLE
Is there any memoization that takes place with Normalizr? Am I going crazy?

### ISSUE THREAD

**Issue by peterpme** [gaearon/normalizr#98]
Hey everyone,

I'm currently in a very weird situation.

Sometimes my entities come back nested, sometimes they don't, so I put this together:

```es6
export function handleNormalize (json, schema) {
  let data

  if (Object.keys(json)[0] === schema.key) {
    data = normalize(json, {
      [schema.key]: schema.type
    })
  } else {
    data = normalize(json, schema.type)
  }

  return data
}
```

Use like so:

```es6
const data = handleNormalize(json, schema)
```

Now, within my component, I render a grid. The data that comes back from this response gets mutated and a `delete` key is added.

Whenever I get more data and run it through `normalize` the `delete` key is present and it slows down my app a TON, because the `delete` key is a React Component.

If you log out `json` before `normalizr`, the data is the way it should be.

AFTER you run `normalizr`, the additional key is present.

I'm running out of ideas!

**Comment by paularmstrong** [comment]
Is `json` the same object the second time you run it through? Can you share a test case that shows this happening?

**Comment by peterpme** [comment]
Hey, thanks for helping out! I will come back to this if this is actually an issue. I might be going crazy :)
