### ISSUE TITLE
How to store additional relational data

### ISSUE THREAD

**Issue by mattii** [gaearon/normalizr#99]
Is there a way to keep data specific to a relation coupled with its respective reference?
E.g. I have projects and each project has a collection of related users with different scopes. One user has the scope `owner`, another one is `contributor` and the last one is a `reviewer`.

```javascript
{
  projects: [{
    id: 1,
    title: 'Some Project',
    users: [{
      id: 7,
      name: 'Dan',
      scope: 'owner'
    }, {
      id: 8,
      name: 'Abe',
      scope: 'contributor'
    },
    ...]
  }]
}
```

Is it possible to normalize this keeping the scope together with its referencing id?

The normalized result should look like this:
```javascript
{
  result: 1,
  entities: {
    projects: {
      1: {
        title: 'Some Project',
        users: [{
          id: 7,
          scope: 'owner' // <-- keep scope coupled with reference
        }, {
          id: 8,
          scope: 'contributor'
        }]
      }
    },
    users: {
      7: { ... },
      8: { ... }
    }
  }
}
```

**Comment by paularmstrong** [comment]
This is not currently possible.

**Comment by paularmstrong** [comment]
Longer thoughts...

You could make separate entity types and infer the schema from the `scope` key. However, then you wouldn't have `users`, but instead, two groups of `owners` and `contributors`. This is probably not what you want.

Is your API forced to be this way, or an you change it? It'd probably make more sense to break out those two types of users into their own arrays.

**Comment by mattii** [comment]
Thanks for your response! Yes, it's possible to change the API and I already thought about a similar solution.

What do you think about this feature in general? Might it be worth to include it into normalizr? Or is it too much an "exotic" edge-case? I'm not using normalizr yet, but if the API-refactoring is too much of a pain, maybe I would try to implement this feature in normalizr and make a PR (only if you think it's worth a try).

**Comment by paularmstrong** [comment]
Handling this is not really how normalizr is intended to work. Personally, I think it's a confusing API design and trying to have normalizr deal with it would cause too much complexity.

**Comment by mattii** [comment]
Yes, you're probably right. Thanks for your feedback!
